### ISSUE TITLE
Possibility to choose nodeport used port

### ISSUE THREAD

**Issue by MikeDevresse** [percona/percona-server-mongodb-operator#1381]
Hi,
I want to deploy a database instance and expose it, my idea was to use a nodeport but I also wanted to choose the port, bur from what I saw there is no way to do that.
I am using the helm chart to deploy my instance but from what I saw it seems to be an issue coming from the operator.
I want to use a nodeport to make things easier and I want to choose the port to keep it consistant between my clusters

**Comment by spron-in** [comment]
Hello @MikeDevresse ,

well, we thought about it. There are a couple of problems with static NodePort:

1. Multiple Replica Set Pods on the same k8s node. It basically means that instead of simple expose section:
```
expose:
  exposeType: NodePort
  port: 11111
```
we will need to specify unique port for each replica set node. Something like this:
```
expose:
  exposeType: NodePort
  ports:
    rs0-0: 11111
    rs0-1: 22222
    rs0-2: 33333
```

2. Another problem is horizontal scaling - adding more nodes into the replica set. If you don't specify NodePort, it means that new node will have a random port. Is it desired? Or we can pre-define ports, which is suboptimal as these ports might be used already at the moment of scaling.


As you see there are bunch of problems and logical loopholes. Do you have any thoughts here?

**Comment by MikeDevresse** [comment]
Why do you need to set a port for each instance ? you only need one port for each RS right ?
I think it can be done like this:
```
replsets:
  - name: rs0
    size: 3
    expose:
      exposeType: NodePort
      nodePort: 30004
  - name: rs1
    size: 3
    expose:
      exposeType: NodePort
      nodePort: 30003
sharding:
  enabled: true
  balancer:
    enabled: true
  configrs:
    size: 3
    expose:
      exposeType: NodePort
      nodePort: 30002
  mongos:
    size: 2
    expose:
      exposeType: NodePort
      nodePort: 30001
``` 
I don't even think it is required for configdb and replicaSets but why not. My use case is to set it on the mongos, and with a static port that I choose which are consistant between environments, I can set approprietly my VPN rules. Right now it is impossible to predict and the port will always be different between environments.

**Comment by spron-in** [comment]
```
  mongos:
    size: 2
    expose:
      exposeType: NodePort
      nodePort: 30001
```

The problem will occur if these two nodes land on the same k8s node. Most probably you are going to avoid that through affinity rules, but it does not mean that the problem is not there.

We can think of implementing it for a narrow use case. Let me discuss it with the team.

Meanwhile, could you pls confirm that you rely on affinity?
