### ISSUE TITLE
Unable to change the replica size, Operator seems to always pick the size as 3 for the StatefulSet

### ISSUE THREAD

**Issue by vjsrinath** [percona/percona-server-mongodb-operator#1416]
### Report

I have been trying to get mongodb deployed in a kubernetes cluster. But the value set for `size` under replsets doesn't seem to have any effect. The operator is always creating the statefulset with 3 pods.

### More about the problem

The operator should respect the passed size and create pods based on it. 

### Steps to reproduce

1. Deploy the pmdb chart using the following values,
The contents of `pmdb.yml`.

```yml
replsets:
  - name: rs0
    size: 2
    podSecurityContext:
      fsGroup: 1001
      runAsGroup: 1001
      runAsUser: 1001
    resources:
      limits:
        cpu: "3900m"
        memory: 14Gi
      requests:
        cpu: 2
        memory: 10Gi
```

Deploy psmdb
```sh
helm install my-db percona/psmdb-db --namespace=percona -f ./deploy/mongodb/pmdb.yml 
```
2. Verify if the expected values are set in the pmdb resource 
    ![image](https://github.com/percona/percona-server-mongodb-operator/assets/5001683/6a5fafe7-34df-4e3b-949e-44c374a89e46)
3. The operator creates statefulset with 3 pods regardless whatever is passed in size

### Versions

1. Kubernetes: 1.28
2. Operator: 1.15.0
3. Database: MongoDB 6
