### ISSUE TITLE
Duplicate StatefulSet ControllerRevision, PerconaServerMongoDB status stucks in "Initializing"

### ISSUE THREAD

**Issue by Fr0s1** [percona/percona-server-mongodb-operator#1557]
### Report

The PerconaServerMongoDB status stucks in "Initializing" because the field "status.updatedReplicas" is always smaller than "status.replicas" which caused by multiple ControllerRevision

![image](https://github.com/percona/percona-server-mongodb-operator/assets/89592818/5840fe4b-3e98-439d-8769-6fa787fd51b5)

### More about the problem

When creating new MongoDB cluster from the Helm chart percona/psmdb-db in ArgoCD, there are two controller revisions of the Config Server and ReplicaSet StatefulSet, 
![image](https://github.com/percona/percona-server-mongodb-operator/assets/89592818/8056c619-e07a-4233-be27-a9f670e82ad4)

The issue happens in the logic of "smart.go" function, the controller compares the StatefulSet field "status.updatedReplicas" with "status.replicas". If it's not equal, then the StatefulSet is not up to date
![image](https://github.com/percona/percona-server-mongodb-operator/assets/89592818/37a7cb94-faec-49a2-971d-1ca25ab4afee)

### Steps to reproduce

1. Install MongoDB Operator in "mongodb-operator" namespace in ArgoCD
![image](https://github.com/percona/percona-server-mongodb-operator/assets/89592818/bf8f4c09-4a28-455a-9fea-6d1b4860535a)

2. Install MongoDB Helm in "mongodb" namespace in ArgoCD
![image](https://github.com/percona/percona-server-mongodb-operator/assets/89592818/24fcaee0-2149-4dfa-abaa-d5e2615466c3)

### Versions

1. Kubernetes: EKS 1.29
2. Operator: 1.16.0
3. Database: 1.16.0

### Anything else?

The issue does not happen with Operator version 1.15.4 and Database version 1.15.3

**Comment by Fr0s1** [comment]
Attach MongoDB DB Helm values
MongoDB Helm values
```
finalizers:
  ## Set this if you want that operator deletes the primary pod last
  - delete-psmdb-pods-in-order
  ## Set this if you want to delete database persistent volumes on cluster deletion
  - delete-psmdb-pvc

fullnameOverride: "mongodb-cluster"

unsafeFlags:
  tls: false
  replsetSize: false
  mongosSize: false
  terminationGracePeriod: false
  backupIfUnhealthy: true

multiCluster:
  enabled: false
  # DNSSuffix: svc.clusterset.local
updateStrategy: SmartUpdate 

upgradeOptions:
  versionServiceEndpoint: https://check.percona.com
  apply: disabled
  schedule: "0 2 * * *"
  setFCV: false

tls:
  mode: preferTLS
  # 90 days in hours
  certValidityDuration: 2160h
  allowInvalidCertificates: true
  issuerConf:
    name: letsencrypt-mongodb
    kind: ClusterIssuer
    group: cert-manager.io
  
pmm:
  enabled: true
  image:
    repository: percona/pmm-client
    tag: 2.41.2
  serverHost: monitoring-service

replsets:
  rs0:
    name: rs0
    size: 3
  
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    
    podDisruptionBudget:
      maxUnavailable: 1
  
    expose:
      enabled: false
      exposeType: ClusterIP
     
    resources:
      limits:
        cpu: "500m"
        memory: "1G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      pvc:
        storageClassName: database-standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi
   
    nonvoting:
      enabled: false
      
      size: 3
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
    
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: "300m"
          memory: "0.5G"
        requests:
          cpu: "300m"
          memory: "0.5G"
      volumeSpec:
        pvc:
          resources:
            requests:
              storage: 3Gi
    arbiter:
      enabled: false
      size: 1
      # serviceAccountName: percona-server-mongodb-operator
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"

sharding:
  enabled: true
  balancer:
    enabled: true

  configrs:
    size: 3
   
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
   
    podDisruptionBudget:
      maxUnavailable: 1
    expose:
      enabled: false
      exposeType: ClusterIP
  
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    volumeSpec:
      pvc:
        resources:
          requests:
            storage: 2Gi

  mongos:
    size: 2

    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
     
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: "300m"
        memory: "0.5G"
      requests:
        cpu: "300m"
        memory: "0.5G"
    expose:
      exposeType: ClusterIP
    
backup:
  enabled: true
  image:
    repository: percona/percona-backup-mongodb
    tag: 2.4.1
 
  storages:
    # minio:
    #   type: s3
    #   s3:
    #     bucket: MINIO-BACKUP-BUCKET-NAME-HERE
    #     region: us-east-1
    #     credentialsSecret: my-cluster-name-backup-minio
    #     endpointUrl: http://minio.psmdb.svc.cluster.local:9000/minio/
    #     prefix: ""
    #   azure-blob:
    #     type: azure
    #     azure:
    #       container: CONTAINER-NAME
    #       prefix: PREFIX-NAME
    #       endpointUrl: https://accountName.blob.core.windows.net
    #       credentialsSecret: SECRET-NAME
  pitr:
    enabled: true
    oplogOnly: true
   
  tasks: []
```
