### ISSUE TITLE
Failed to delete history backup data in minio

### ISSUE THREAD

**Issue by Cookiery** [percona/percona-server-mongodb-operator#1579]
### Report

Failed to delete history backup data in minio.

pbm only deleted the history json file, but the directory file was not successfully deleted, and I doubt it was because --force was not added.

This is my values.yaml file
```
backup:
  enabled: true
  image:
    repository: harbor.devops.narwal.com/public_mirror/percona-backup-mongodb
    tag: 2.4.1
  storages:
    minio:
      type: s3
      s3:
        bucket: testing
        region: us-east-1
        credentialsSecret: backup-credentials-minio
        endpointUrl: https://10.10.180.14:9700/
        prefix: "mongodb"
        insecureSkipTLSVerify: false
  pitr:
    enabled: true
    oplogOnly: false
tasks:
  - name: daily-minio-s3
    enabled: true
    schedule: "0 */1 * * *"
    keep: 2
    storageName: minio
    compressionType: gzip
    type: physical
```

### More about the problem

Permissions are all allowed

### Steps to reproduce

1. 
2. 
3. 

### Versions

1. Kubernetes
2. Operator
3. Database
