### ISSUE TITLE
No way to turn off authentication 

### ISSUE THREAD

**Issue by aqeelat** [percona/percona-server-mongodb-operator#1619]
### Report

We cannot disable authentication even if we pass this as a conf
```conf
security:
  authorization: "disabled"
```

### More about the problem

`--auth` is being passed, which overrides the mongod.conf

https://github.com/percona/percona-server-mongodb-operator/blob/f10e1aa6286cb313bee882e6a25938e2b9106b58/pkg/psmdb/container.go#L176-L184

### Steps to reproduce

Deploy with:
```
spec:
  ...
  replsets:
    - name: rs0
      size: 3
      configuration: |
        security:
          authorization: "disabled"
```

### Versions

1. Kubernetes: 1.28
2. Operator: 1.16.1
3. Database: 7.0.8-5

### Anything else?

This would be fine if there'a a way to create users using the crd.
