### ISSUE TITLE
PerconaServerMongoDBRestore pbm 2.6.0 get S3 object header: NoCredentialProviders: no valid providers in chain. Deprecated

### ISSUE THREAD

**Issue by holubnychyi** [percona/percona-server-mongodb-operator#1724]
### Report

Backup and restore works fine with pbm 2.5.0. Once I upgrade percona-backup-mongodb:2.5.0 to the percona-backup-mongodb:2.6.0 or 2.7.0, I get error for PerconaServerMongoDBRestore only. PerconaServerMongoDBBackup works properly in all versions. 
```
[PerconaServerMongoDBRestore pbm 2.6.0 get S3 object header: NoCredentialProviders: no valid providers in chain. Deprecated]
```

### More about the problem

The backup storage configuration:
```
backup:
  storages:
    juicefs:
      type: s3
      s3:
        region: europe-west3
        bucket: juicefs-enc-sc
        uploadPartSize: 402653184
        prefix: backup/mongo-pbm/environment
        endpointUrl: http://s3-juicefs-enc-sc.juicefs.svc.cluster.local:9000
        credentialsSecret: default-backup-s3
```

### Steps to reproduce

1. version components and configuration are mentioned. 
2. Upgrade pbm to 2.6.0 or 2.7.0 and run PerconaServerMongoDBRestore

### Versions

storage: JuiceFS.

Percona Server MongoDB Operator
helm charts:
psmdb-operator-1.17.1
psmdb-db-1.17.0
crd: 0.16.3

images:
percona-server-mongodb-operator:1.17.1
percona-backup-mongodb:2.5.0 -> percona-backup-mongodb:2.6.0
