### ISSUE TITLE
Compatibility issue with Linkerd

### ISSUE THREAD

**Issue by klauserber** [percona/percona-server-mongodb-operator#1768]
### Report

I am experiencing a compatibility issue between the Percona MongoDB Operator and Linkerd.

### More about the problem

The MongoDB instance should deploy successfully with Linkerd injection enabled.

### Steps to reproduce

1. **Create a namespace with Linkerd injection enabled:**

    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        kubernetes.io/metadata.name: myapp-dev
      name: myapp-dev
    ```

2. **Install the operator following the documentation:**
   - [Percona MongoDB Operator Documentation](https://docs.percona.com/percona-operator-for-mongodb/kubernetes.html)

3. **Deploy a minimal MongoDB instance:**

    ```yaml
    apiVersion: psmdb.percona.com/v1
    kind: PerconaServerMongoDB
    metadata:
      name: minimal-cluster
    spec:
      crVersion: 1.18.0
      image: perconalab/percona-server-mongodb-operator:main-mongod7.0
      unsafeFlags:
        replsetSize: true
        mongosSize: true
      upgradeOptions:
        apply: disabled
        schedule: "0 2 * * *"
      secrets:
        users: minimal-cluster
      replsets:
      - name: rs0
        size: 3
        volumeSpec:
          persistentVolumeClaim:
            resources:
              requests:
                storage: 3Gi
    ```

### Versions

1. Kubernetes: v1.30.6-gke.1125000
2. Operator: 1.18.0
3. Database: 7
4. Linkerd: 2.14.10

### Anything else?

**Workaround:**

To resolve the issue, patch the operator Deployment to disable Linkerd injection:

```bash
kubectl -n myapp-dev patch deployment percona-server-mongodb-operator -p '{"spec": {"template": {"metadata": {"annotations": {"linkerd.io/inject": "disabled"}}}}}'

Then, delete the PerconaServerMongoDB CR and apply it again. The pods should come up correctly.
