### ISSUE TITLE
Make arbiter and nonvoting sections in CRD optional

### ISSUE THREAD

**Issue by BasJ93** [percona/percona-server-mongodb-operator#1815]
### Proposal

Make the arbiter and nonvoting config sections optional, so that they don't need to be filled out when these options have been disabled.

I would propose that the `enabled` field is required, but all other fields are optional. The operator should check the optional fields when `enabled` is set to true.

### Use-Case

This would reduce the lines of configuration in the deployed manifest when features are not used. Reduced lines are more readable, and configuration sections are more compact.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by egegunes** [comment]
@BasJ93 arbiter and nonVoting sections are already optional. You can deploy a minimal cluster:
```
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: cluster1
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
spec:
  crVersion: 1.21.0
  image: perconalab/percona-server-mongodb-operator:main-mongod8.0
  updateStrategy: SmartUpdate
  replsets:
    - name: rs0
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
```
