### ISSUE TITLE
PMM3 client can not write pmm.yaml config

### ISSUE THREAD

**Issue by PatrickWolleb** [percona/percona-server-mongodb-operator#1865]
### Report

PMM3 agent can not read or write pmm.yaml config. File system differs from pmm-agent config path.

**Actual**
pmm fails to connect to pmm server. 
```
Config file /usr/local/percona/pmm2/config/pmm-agent.yaml is not writable: no such file or directory.time="2025-03-14T14:53:54.287+00:00" level=info msg="'pmm-agent setup' exited with 1" component=entrypoint
```

**Expected**
pmm agent can connect to pmm server

**More info**
When checking the file system the directory on the file system ist different from the value being passed as env var.  /usr/local/percona/pmm2 instead of  /usr/local/percona/pmm 

### More about the problem

Config file /usr/local/percona/pmm2/config/pmm-agent.yaml is not writable: no such file or directory.time="2025-03-14T14:53:54.287+00:00" level=info msg="'pmm-agent setup' exited with 1" component=entrypoint

### Steps to reproduce

1. install pmm server 3.0.0
2. Install percona operator 
3. create cluster with pmm agent 3.0.0 enabled 

### Versions

1. Kubernetes 1.31
2. Operator  1.19.1
4. Database 6.0.20

### Anything else?

When checking the file system the directory on the file system ist different from the value being passed as env var.  /usr/local/percona/pmm2 instead of  /usr/local/percona/pmm

**Comment by hors** [comment]
PSMDB operator does not support PMM3. We will add support in PSMDBO 1.21.0.

**Comment by dbazhenov** [comment]
JIRA issue where PMM 3 support will be implemented so you can track.
https://perconadev.atlassian.net/browse/K8SPSMDB-1268

**Comment by Thijmen** [comment]
I am very much looking forward to this, any ETA on this?

**Comment by nmarukovich** [comment]
We added support for PMM3 but it is not released yet. We plan to release it in 3 weeks.

**Comment by odorT** [comment]
any updates? 🙂

**Comment by hors** [comment]
Hi @odorT  we’ve released PSMDB Operator v1.21.0. Please begin planning the upgrade of your clusters accordingly.

**Comment by kuhnroyal** [comment]
I have update operator, CRDs and cluster to 1.21.0 and now I get this error in the pmm sidecar. Anything I am missing?

**Comment by hors** [comment]
> I have update operator, CRDs and cluster to 1.21.0 and now I get this error in the pmm sidecar. Anything I am missing?

@kuhnroyal please check the official documentation https://docs.percona.com/percona-operator-for-mongodb/monitoring-tutorial.html?h=#create-a-secret , as you can see, you need to get and set PMM_SERVER_TOKEN into the secret.

**Comment by odorT** [comment]
upgraded to latest version of psmdb operator and pmm. still same error

**Comment by hors** [comment]
> upgraded to latest version of psmdb operator and pmm. still same error

@odorT please check the official documentation https://docs.percona.com/percona-operator-for-mongodb/monitoring-tutorial.html?h=#create-a-secret , as you can see, you need to get PMM_SERVER_TOKEN from pmm server and then set it into the secret.

**Comment by odorT** [comment]
already did, container looks for PMM_SERVER_USER and PMM_SERVER_PASSWORD env variables

**Comment by hors** [comment]
> already did, container looks for PMM_SERVER_USER and PMM_SERVER_PASSWORD env variables 

You need to set PMM_SERVER_TOKEN and remove the old keys.

**Comment by odorT** [comment]
yes, removed them, and now container fails to start because those keys are not set.

here is my psmdb CRD:

```
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  labels:
    argocd.argoproj.io/instance: percona
  name: REDACTED
  namespace: percona
spec:
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:2.11.0
    pitr:
      enabled: true
      oplogOnly: false
    storages:
      aws-s3:
        main: true
        s3:
          bucket: REDACTED
          credentialsSecret: percona-common-secret
          prefix: REDACTED
          region: us-east-2
        type: s3
    tasks:
      - compressionType: gzip
        enabled: true
        keep: 30
        name: logical-daily-aws-s3
        schedule: 50 14 * * *
        storageName: aws-s3
        type: logical
      - compressionType: gzip
        enabled: true
        keep: 24
        name: logical-monthly-aws-s3
        schedule: 50 16 1 * *
        storageName: aws-s3
        type: logical
      - compressionType: gzip
        enabled: true
        keep: 7
        name: incremental-base-daily-aws-s3
        schedule: 50 15 * * *
        storageName: aws-s3
        type: incremental-base
      - compressionType: gzip
        enabled: true
        keep: 48
        name: incremental-half-hourly-aws-s3
        schedule: '*/30 * * * *'
        storageName: aws-s3
        type: incremental
  enableVolumeExpansion: true
  image: percona/percona-server-mongodb:6.0.8
  imagePullPolicy: Always
  multiCluster:
    enabled: false
  pause: false
  pmm:
    enabled: true
    image: percona/pmm-client:3.4.1
    serverHost: monitoring-service
  replsets:
    - affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      arbiter:
        enabled: false
        size: 1
      expose:
        enabled: true
        type: ClusterIP
      name: rs0
      nonvoting:
        enabled: false
        size: 1
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: '3.5'
          memory: 4.5Gi
        requests:
          cpu: '0.5'
          memory: 0.5G
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 10Gi
  secrets:
    users: REDACTED-psmdb-secret
  sharding:
    enabled: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: disabled
  users:
    - db: REDACTED
      name: REDACTED
      passwordSecretRef:
        key: REDACTED
        name: REDACTED-psmdb-secret
      roles:
        - db: REDACTED
          name: readWrite
```

**Comment by hors** [comment]
> yes, removed them, and now container fails to start because those keys are not set.
> 
> here is my psmdb CRD:
> 
> ```
> apiVersion: psmdb.percona.com/v1
> kind: PerconaServerMongoDB
> metadata:
>   labels:
>     argocd.argoproj.io/instance: percona
>   name: REDACTED
>   namespace: percona
> spec:
>   backup:
>     enabled: true
>     image: percona/percona-backup-mongodb:2.11.0
>     pitr:
>       enabled: true
>       oplogOnly: false
>     storages:
>       aws-s3:
>         main: true
>         s3:
>           bucket: REDACTED
>           credentialsSecret: percona-common-secret
>           prefix: REDACTED
>           region: us-east-2
>         type: s3
>     tasks:
>       - compressionType: gzip
>         enabled: true
>         keep: 30
>         name: logical-daily-aws-s3
>         schedule: 50 14 * * *
>         storageName: aws-s3
>         type: logical
>       - compressionType: gzip
>         enabled: true
>         keep: 24
>         name: logical-monthly-aws-s3
>         schedule: 50 16 1 * *
>         storageName: aws-s3
>         type: logical
>       - compressionType: gzip
>         enabled: true
>         keep: 7
>         name: incremental-base-daily-aws-s3
>         schedule: 50 15 * * *
>         storageName: aws-s3
>         type: incremental-base
>       - compressionType: gzip
>         enabled: true
>         keep: 48
>         name: incremental-half-hourly-aws-s3
>         schedule: '*/30 * * * *'
>         storageName: aws-s3
>         type: incremental
>   enableVolumeExpansion: true
>   image: percona/percona-server-mongodb:6.0.8
>   imagePullPolicy: Always
>   multiCluster:
>     enabled: false
>   pause: false
>   pmm:
>     enabled: true
>     image: percona/pmm-client:3.4.1
>     serverHost: monitoring-service
>   replsets:
>     - affinity:
>         antiAffinityTopologyKey: kubernetes.io/hostname
>       arbiter:
>         enabled: false
>         size: 1
>       expose:
>         enabled: true
>         type: ClusterIP
>       name: rs0
>       nonvoting:
>         enabled: false
>         size: 1
>       podDisruptionBudget:
>         maxUnavailable: 1
>       resources:
>         limits:
>           cpu: '3.5'
>           memory: 4.5Gi
>         requests:
>           cpu: '0.5'
>           memory: 0.5G
>       size: 3
>       volumeSpec:
>         persistentVolumeClaim:
>           resources:
>             requests:
>               storage: 10Gi
>   secrets:
>     users: REDACTED-psmdb-secret
>   sharding:
>     enabled: false
>   updateStrategy: SmartUpdate
>   upgradeOptions:
>     apply: disabled
>   users:
>     - db: REDACTED
>       name: REDACTED
>       passwordSecretRef:
>         key: REDACTED
>         name: REDACTED-psmdb-secret
>       roles:
>         - db: REDACTED
>           name: readWrite
> ```

In secret 

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-name
type: Opaque
stringData:
  ....
  PMM_SERVER_TOKEN: "valid token"
```

You need to have valid token from pmm3 server.

**Comment by odorT** [comment]
```
apiVersion: v1
data:
  PMM_SERVER_PASSWORD: REDACTED
  PMM_SERVER_TOKEN: REDACTED
  PMM_SERVER_USER: REDACTED
kind: Secret
metadata:
  annotations:
    percona.com/REDACTED-belong-hash: REDACTED
  name: REDACTED-psmdb-secret
  namespace: percona
type: Opaque
```

yes we have it in secret
