### ISSUE TITLE
EACCES: permission denied with custom user and group ID

### ISSUE THREAD

**Issue by lsoica** [percona/percona-server-mongodb-operator#1947]
### Report

For the following CR config, with non root uid and gid:
```
  replsets:
  - containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    name: rs0
    podSecurityContext:
      fsGroup: 10001
      runAsGroup: 10001
      runAsNonRoot: true
      runAsUser: 10001
```

perconaservermongodbs CR status ends up in error:
```
status:
  conditions:
  - lastTransitionTime: "2025-05-28T11:29:21Z"
    message: 'handleReplsetInit: no mongod containers in running state'
    reason: ErrorReconcile
    status: "True"
    type: error
  message: |
    Error: handleReplsetInit: exec add admin user: command terminated with exit code 1 / Warning: Could not access file: EACCES: permission denied, mkdir '/.mongodb'
     / MongoServerError: not primary
  ready: 0
  replsets:
    rs0:
      ready: 0
      size: 0
  size: 0
  state: error
```

### More about the problem

Expected behavior: Operator should be able to initialize MongoDB replica set even if the ephemeral storage is read only

### Versions

1. Kubernetes v1.29.9+k3s1
2. Operator 1.19.1
3. Database tested with 8.0.8-3 and 7.0.18-11

LE: The critical error, "MongoServerError: not primary" comes from the fact that I did not configure clusterServiceDNSSuffix. With that in place, the CR is successfully reconciled; users are created as well. There's still the permission denied warning, but it does not block the reconciliation.
