### ISSUE TITLE
Infinite "FailedUpdateStatus" error on replicaset service

### ISSUE THREAD

**Issue by sunguck** [percona/percona-server-mongodb-operator#1952]
### Report

I have created replica-set with `psmdb-operator 1.20.0` using following expose attributes.
```
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: alpha-eksmongo70-rs
  finalizers: null
spec:
  crVersion: 1.20.0
  ...
  replsets:
    - name: shard01
      ...
      expose:
        enabled: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-security-groups: "eks-default,mongodb"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
    ...
```

"kubectl get svc" command shows services are created well. 
```
NAME                            TYPE           CLUSTER-IP       EXTERNAL-IP                 PORT(S)           AGE
alpha-eksmongo70-rs-shard01     ClusterIP      None             <none>                      27017/TCP         8h
alpha-eksmongo70-rs-shard01-0   LoadBalancer   172.20.215.11    k8s-mongodbt-alphaeks-...   27017:31323/TCP   16h
alpha-eksmongo70-rs-shard01-1   LoadBalancer   172.20.137.234   k8s-mongodbt-alphaeks-...   27017:30732/TCP   16h
alpha-eksmongo70-rs-shard01-2   LoadBalancer   172.20.98.186    k8s-mongodbt-alphaeks-...   27017:31248/TCP   16h
```
But "kubectl describe service alpha-eksmongo70-rs-shard01" prints following warning messages. And this warning of replicaset service is never disappeared.
```
Events:
  Type     Reason              Age                    From     Message
  ----     ------              ----                   ----     -------
  Warning  FailedUpdateStatus  11m (x9607 over 108d)  service  Failed update status due to failed to update service status: mongodb-test/alpha-eksmongo70-rs-shard01: Service "alpha-eksmongo70-rs-shard01" is invalid: status.loadBalancer.ingress: Forbidden: may only be used when `spec.type` is 'LoadBalancer'
```

But each replicaset member's services(`alpha-eksmongo70-rs-shard01-0, alpha-eksmongo70-rs-shard01-1, alpha-eksmongo70-rs-shard01-2`) are fine.

After briefly reviewing the source code of the psmdb-operator, 
I found that during the creation of the replica-set service, all annotations defined in replsets.expose.annotations are copied to the replica set service's annotations. 
As a result, all AWS NLB-related annotations from replsets.expose.annotations are passed to the replica set service. ( [here1](https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/controller/perconaservermongodb/service.go#L37-L39) and [here2](https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/psmdb/service.go#L70-L74) and [here3](https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/controller/perconaservermongodb/psmdb_controller.go#L1521) )
Although the exposeType of the replica set service is ClusterIP (headless service), it is likely that the AWS NLB controller is attempting to create an AWS LoadBalancer and update the status.loadBalancer.ingress field, which is causing this error to occur repeatedly.

I am not sure this is AWS NLB controller's bug or not, anyway I think psmdb-operator should not pass nlb related anotations to replica-set service's metadata (e.g. following example code).
```
func removeKeysWithPrefix(m map[string]string, prefix string) {
        if m != nil {
                for key := range m {
                        if strings.HasPrefix(key, prefix) {
                                delete(m, key)
                        }
                }
        }
}

// https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/controller/perconaservermongodb/psmdb_controller.go#L1521-L1544
func (r *ReconcilePerconaServerMongoDB) createOrUpdateSvc(ctx context.Context, cr *api.PerconaServerMongoDB, svc *corev1.Service, saveOldMeta bool) error {
        if svc.Spec.Type!=corev1.ServiceTypeLoadBalancer {
                // Remove following nlb related annotations
                // "service.beta.kubernetes.io/aws-load-balancer-nlb-target-type"
                // "service.beta.kubernetes.io/aws-load-balancer-type"
                // "service.beta.kubernetes.io/aws-load-balancer-security-groups"
                // "service.beta.kubernetes.io/aws-load-balancer-target-group-attributes"
                removeKeysWithPrefix(svc.Annotations, "service.beta.kubernetes.io/aws-load-balancer")
        }

        if !saveOldMeta && len(cr.Spec.IgnoreAnnotations) == 0 && len(cr.Spec.IgnoreLabels) == 0 {
                return r.createOrUpdate(ctx, svc)
        }
        oldSvc := new(corev1.Service)
        err := r.client.Get(ctx, types.NamespacedName{
                Name:      svc.GetName(),
                Namespace: svc.GetNamespace(),
        }, oldSvc)
        if err != nil {
                if k8serrors.IsNotFound(err) {
                        return r.createOrUpdate(ctx, svc)
                }
                return errors.Wrap(err, "get object")
        }

        if saveOldMeta {
                svc.SetAnnotations(util.MapMerge(oldSvc.GetAnnotations(), svc.GetAnnotations()))
                svc.SetLabels(util.MapMerge(oldSvc.GetLabels(), svc.GetLabels()))
        }
        setIgnoredAnnotations(cr, svc, oldSvc)
        setIgnoredLabels(cr, svc, oldSvc)

        if svc.Spec.Type!=corev1.ServiceTypeLoadBalancer {
                // Remove nlb related annotations
                removeKeysWithPrefix(svc.Annotations, "service.beta.kubernetes.io/aws-load-balancer")
        }

        return r.createOrUpdate(ctx, svc)
}

// In Service() and ExternalService() function, Annotation should be copied deeply (Not just assign reference).
// https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/psmdb/service.go#L24
func Service(cr *api.PerconaServerMongoDB, replset *api.ReplsetSpec) *corev1.Service {
        ls := naming.ServiceLabels(cr, replset)

        // DeepCopy for annotations
        annotations := make(map[string]string)
        for k, v := range replset.Expose.ServiceAnnotations {
                annotations[k] = v
        }

        svc := &corev1.Service{
                TypeMeta: metav1.TypeMeta{
                        APIVersion: "v1",
                        Kind:       "Service",
                },
                ObjectMeta: metav1.ObjectMeta{
                        Name:        cr.Name + "-" + replset.Name,
                        Namespace:   cr.Namespace,
                        Annotations: annotations,
                },
                Spec: corev1.ServiceSpec{
                        Ports: []corev1.ServicePort{
                                {
                                        Name:       mongodPortName,
                                        Port:       replset.GetPort(),
                                        TargetPort: intstr.FromInt(int(replset.GetPort())),
                                },
                        },
                        ClusterIP: "None",
                        Selector:  ls,
                },
        }
        ...
}

// https://github.com/percona/percona-server-mongodb-operator/blob/v1.20.0/pkg/psmdb/service.go#L64
func ExternalService(cr *api.PerconaServerMongoDB, replset *api.ReplsetSpec, podName string) *corev1.Service {
        // DeepCopy for annotations
        annotations := make(map[string]string)
        for k, v := range replset.Expose.ServiceAnnotations {
                annotations[k] = v
        }

        svc := &corev1.Service{
                TypeMeta: metav1.TypeMeta{
                        Kind:       "Service",
                        APIVersion: "v1",
                },
                ObjectMeta: metav1.ObjectMeta{
                        Name:        podName,
                        Namespace:   cr.Namespace,
                        Annotations: annotations,
                },
        }
        ...
}    
```

### More about the problem

```
Events:
  Type     Reason              Age                    From     Message
  ----     ------              ----                   ----     -------
  Warning  FailedUpdateStatus  11m (x9607 over 108d)  service  Failed update status due to failed to update service status: mongodb-test/alpha-eksmongo70-rs-shard01: Service "alpha-eksmongo70-rs-shard01" is invalid: status.loadBalancer.ingress: Forbidden: may only be used when `spec.type` is 'LoadBalancer'
```

### Steps to reproduce

1. Create new replica-set using LoadBalancer(AWS NLB) with following annotations.
```
      expose:
        enabled: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-security-groups: "eks-default,mongodb"
          service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: preserve_client_ip.enabled=false
```
2. Check replica-set's service and check warning message (kubectl describe replicaset-shard01)

### Versions

1. Kubernetes `v1.31.7-eks-4096722`
2. Operator `1.20.0` or `1.19.0`
3. Database `Percona Server for MongoDB`
